name: faani
description: An application to connect tailor and customer, it promote traditionnal suit. We can book inside and follow best tailor
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  # google_fonts: ^6.0.0
  # go_router: ^13.2.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  provider: ^6.0.5
  # firebase_ui_auth: ^1.9.1
  intl_phone_field: ^3.2.0
  pinput: ^4.0.0
  camera: ^0.10.5+5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.20
  firebase_in_app_messaging: ^0.7.4+18
  image_picker: ^1.0.4
  url_launcher: ^6.0.12
  # sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.1.0
  firebase_storage: ^11.6.10
  path: ^1.8.3
  intl: ^0.19.0
  cached_network_image: ^3.1.0
  path_provider: ^2.1.1
  share_plus: ^8.0.2
  dio: ^5.3.3
  image_gallery_saver: '^2.0.3'
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  # animate_do: ^3.1.2
  flutter_spacer: ^1.0.3
  firebase_app_check: ^0.2.1+18
  persistent_bottom_nav_bar_v2: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/ic_launcher.png'
  background_color: '#F3755F'
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Mochiy Pop One
      fonts:
        - asset: assets/fonts/MochiyPopOne-Regular.ttf
          weight: 400
